const HOST_URL = 'https://bpdlh.id/aksesdanalh/public/api/';
const CLIENT_ID = '6684d93e8cb88';
const CLIENT_ID_SECRET = 'vc8U5EaZ3bUKV9ka4PsNLrpVGWZVVpyZsAhmnRWO'
const RECAPTCHA_SITE_KEY="6Le5y6opAAAAAJCSxqqGz07NpWtB9v8A7H9Q1rym"
const RECAPTCHA_SECRET_KEY="6Le5y6opAAAAAPHEm7394JhjPnu5dB9dkR5stc9x"

export {  HOST_URL, CLIENT_ID, CLIENT_ID_SECRET, RECAPTCHA_SECRET_KEY, RECAPTCHA_SITE_KEY };