export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const FORGOT_PASSWORD_BEGIN = 'FORGOT_PASSWORD_BEGIN';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_BEGIN = 'RESET_PASSWORD_BEGIN';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/////////////////////////////////////////////////////////////////////////////////////////
export const GET_TEMATIK_KEGIATAN_BEGIN = 'GET_TEMATIK_KEGIATAN_BEGIN';
export const GET_TEMATIK_KEGIATAN = 'GET_TEMATIK_KEGIATAN';
export const GET_TEMATIK_KEGIATAN_ERROR = 'GET_TEMATIK_KEGIATAN_ERROR';

export const GET_SUB_TEMATIK_KEGIATAN_BEGIN = 'GET_TEMATIK_KEGIATAN_BEGIN';
export const GET_SUB_TEMATIK_KEGIATAN = 'GET_TEMATIK_KEGIATAN';
export const GET_SUB_TEMATIK_KEGIATAN_ERROR = 'GET_SUB_TEMATIK_KEGIATAN_ERROR'; 

export const GET_PAKET_KATEGORI_DATA_BEGIN = 'GET_PAKET_KATEGORI_DATA_BEGIN';
export const GET_PAKET_KATEGORI_DATA = 'GET_PAKET_KATEGORI_DATA';
export const GET_PAKET_KATEGORI_DATA_ERROR = 'GET_SUB_TEMATIK_KEGIATAN_ERROR'; 

//////////////////////////////////////////////////////////////////////////////////////////

export const GET_KELURAHAN_BEGIN = 'GET_KELURAHAN_BEGIN';
export const GET_KELURAHAN = 'GET_KELURAHAN';
export const GET_KELURAHAN_ERROR = 'GET_KELURAHAN_ERROR';

export const GET_KECAMATAN_BEGIN = 'GET_KECAMATAN_BEGIN';
export const GET_KECAMATAN = 'GET_KECAMATAN';
export const GET_KECAMATAN_ERROR = 'GET_KECAMATAN_ERROR'; 

export const GET_KOTA_BEGIN = 'GET_KOTA_BEGIN';
export const GET_KOTA = 'GET_KOTA';
export const GET_KOTA_ERROR = 'GET_KOTA_ERROR'; 

export const GET_PROVINSI_BEGIN = 'GET_PROVINSI_BEGIN';
export const GET_PROVINSI = 'GET_PROVINSI';
export const GET_PROVINSI_ERROR = 'GET_PROVINSI_ERROR'; 

export const GET_PROGRESS_KEGIATAN_BEGIN = 'GET_PROGRESS_KEGIATAN_BEGIN';
export const GET_PROGRESS_KEGIATAN = 'GET_PROGRESS_KEGIATAN';
export const GET_PROGRESS_KEGIATAN_ERROR = 'GET_PROGRESS_KEGIATAN_ERROR'; 

export const GET_RIWAYAT_PENGAJUAN_BEGIN = 'GET_RIWAYAT_PENGAJUAN_BEGIN';
export const GET_RIWAYAT_PENGAJUAN = 'GET_RIWAYAT_PENGAJUAN';
export const GET_RIWAYAT_PENGAJUAN_ERROR = 'GET_RIWAYAT_PENGAJUAN_ERROR'; 

export const GET_KELOMPOK_MASYARAKAT_BEGIN = 'GET_KELOMPOK_MASYARAKAT_BEGIN';
export const GET_KELOMPOK_MASYARAKAT = 'GET_KELOMPOK_MASYARAKAT';
export const GET_KELOMPOK_MASYARAKAT_ERROR = 'GET_KELOMPOK_MASYARAKAT_ERROR'; 

export const GET_DATA_VERIFIKASI_BEGIN = 'GET_DATA_VERIFIKASI_BEGIN';
export const GET_DATA_VERIFIKASI = 'GET_DATA_VERIFIKASI';

export const GET_DATA_VALIDASI_BEGIN = 'GET_DATA_VALIDASI_BEGIN';
export const GET_DATA_VALIDASI = 'GET_DATA_VALIDASI';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

export const SET_EDIT_JOB = 'SET_EDIT_JOB';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';

/////////////////////////////////////////////////////////////////////////////////////////
export const GET_LIST_USER_BEGIN = 'GET_LIST_USER_BEGIN';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';

export const SORT_COLUMN = 'SORT_COLUMN';
export const SET_ITEM_PER_PAGE = 'SET_ITEM_PER_PAGE';
export const SET_SEARCH = 'SET_SEARCH';

export const MANAGE_USER_BEGIN = 'MANAGE_USER_BEGIN';
export const MANAGE_USER_SUCCESS = 'MANAGE_USER_SUCCESS';
export const MANAGE_USER_ERROR = 'MANAGE_USER_ERROR';

export const GET_LIST_DATA_BEGIN = 'GET_LIST_DATA_BEGIN';
export const GET_LIST_DATA_SUCCESS = 'GET_LIST_DATA_SUCCESS';

export const DELETE_DATA_BEGIN = 'DELETE_DATA_BEGIN'
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR'

export const UPDATE_DATA_BEGIN = 'DELETE_DATA_BEGIN'
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_ERROR = 'DELETE_DATA_ERROR'

export const CREATE_DATA_BEGIN = 'CREATE_DATA_BEGIN';
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS';
export const CREATE_DATA_ERROR = 'CREATE_DATA_ERROR';
/////////////////////////////////////////////////////////////////////////////////////////

export const TOGGLE_SHARE_PROFILE = 'TOGGLE_SHARE_PROFILE';
export const TOGGLE_PROFILE_MODAL = 'TOGGLE_PROFILE_MODAL';
export const TOGGLE_FORM_MODAL = 'TOGGLE_FORM_MODAL';
export const TOGGLE_DETAIL_PROGRESS_MODAL = 'TOGGLE_DETAIL_PROGRESS_MODAL';
export const TOGGLE_VALIDASI_MODAL = 'TOGGLE_VALIDASI_MODAL';
export const TOGGLE_VERIFIKASI_MODAL = 'TOGGLE_VERIFIKASI_MODAL';

/////////////////////////////////////////////////////////////////////////////////////////

export const GET_NOTIFICATIONS_USERNAME_BEGIN = 'GET_NOTIFICATIONS_USERNAME_BEGIN';
export const GET_NOTIFICATIONS_USERNAME_SUCCESS = 'GET_NOTIFICATIONS_USERNAME_SUCCESS';

export const EDIT_USER_VIEW_RULE_BEGIN = 'EDIT_USER_VIEW_RULE_BEGIN'
export const EDIT_USER_VIEW_RULE_SUCCESS = 'EDIT_USER_VIEW_RULE_SUCCESS'
export const EDIT_USER_VIEW_RULE_ERROR = 'EDIT_USER_VIEW_RULE_ERROR'

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

/////////////////////////////////////////////////////////////////////////////////////////

export const POST_FORM_PENGAJUAN_BEGIN = "POST_FORM_PENGAJUAN_BEGIN"
export const POST_FORM_PENGAJUAN = "POST_FORM_PENGAJUAN"
export const POST_FORM_PENGAJUAN_ERROR = "POST_FORM_PENGAJUAN_ERROR"

export const POST_FORM_VERIFIKASI_BEGIN = "POST_FORM_VERIFIKASI_BEGIN"
export const POST_FORM_VERIFIKASI = "POST_FORM_VERIFIKASI"
export const POST_FORM_VERIFIKASI_ERROR = "POST_FORM_VERIFIKASI_ERROR"